/**
 * Created by vilin on 1/25/2017.
 */
app.controller("homeController", ["$scope", "$http", "$window", function ($scope, $http, $window) {
    
    //TODO make index controller and ui-router
    $scope.urlApi = 'http://www.showme.com/api/explore/recommended?topic=all';
    $scope.activeSearch = false;
    $scope.searchInputFocus = false;
    $scope.searched = '';
    
    $scope.featuredPeopleVideosArray = ['1', '1408', '8421'];
    
    $http.get($scope.urlApi)
        .then(function (data) {
            $scope.featuredPeopleObj = data.data.data[1];
            $scope.featuredPeopleArray = [];
            $scope.featuredPeopleArray.push($scope.featuredPeopleObj.items[2]);
            $scope.featuredPeopleArray.push($scope.featuredPeopleObj.items[4]);
            $scope.featuredPeopleArray.push($scope.featuredPeopleObj.items[1]);
            
            
            $scope.popularShowMesObj = data.data.data[2];
            $scope.popularShowMesArray = $scope.popularShowMesObj.items;
            console.log($scope.featuredPeopleArray);
        });
    
    
    $scope.categoriesArray = ['math', 'science', 'language', 'social studies', 'music', 'art']
    
    $scope.testimonialsArray = [
        {
            name: "Mike Poliquin",
            signature: "Math Teacher (Alg 2, Pre-Calculus, Calculus) at Maur Hill - Mount Academy Quiz Bowl Coach. @mike_poliquin",
            testimonial: "I am using ShowMe to create videos for flipped math classrooms. I have always liked the core product, but now that I am exporting the videos so that I can add other features, I especially appreciate how well it works with other applications for the flipped classroom. If you're just getting started using video content to reach more of your students more often, ShowMe is a terrific place to launch.",
            profilePictureUrl: "./public/images/testimonials/mike_poliquin.jpg"
        },
        {
            name: "Mallory Dyer",
            signature: "Professor of Mathematics, Online Math Tutor and App Developer. @mathbyma",
            testimonial: "ShowMe is an amazing tool to use not only for lectures in my classroom but also for my hybrid and online classes. I love being able to use various colors to help the visual learners and keep my students attention. I also like that I can graph and pull in pictures. The best part about it, is that it records the entire thing- making it easy for students to go back and watch.",
            profilePictureUrl: "./public/images/testimonials/mallory_dyer.jpg"
        },
        {
            name: "Matt Evans",
            signature: "Professor,  Physics & Astronomy",
            testimonial: "The students really appreciate having access to review materials generated by me based on our lectures and assignments, and ShowMe has the tools to make this easy and for me look like a professional.",
            profilePictureUrl: "./public/images/testimonials/matt_evans.jpg"
        },
        {
            name: "Leslie Stevens",
            signature: "Teaching sixth grade math in Middle School. @les_day_stevens",
            testimonial: "ShowMe helps me provide extra help and reinforcement of math concepts for students to use at home.   I also use this great tool to communicate information to parents, provide tutorials on education technology, tutor individual students, enhance lessons with visuals, and provide independent study and challenging enrichment tasks for students.",
            profilePictureUrl: "./public/images/testimonials/leslie_stevens.jpg"
        },
        {
            name: "Patrick Drake",
            signature: "Teaches math at Halifax NS Canada @MrDrakeMathHelp",
            testimonial: "ShowMe has been invaluable to my teaching methods to help students who may need just that extra little nugget of information in the form of a video from myself or from any of the other wonderful contributors.",
            profilePictureUrl: "./public/images/testimonials/patrick_drake.jpg"
        },
        {
            name: "Colin O'Haire",
            signature: "Math teacher at Dougherty Valley High School in San Ramon, CA.",
            testimonial: "ShowMe has been a fantastic resource for me.  I plug my ipad into my projector and my students get a very robust and visually appealing smart board service for 6 bucks a month.  Also, I record a lecture for each of my classes every day of class.  Absent students are always caught up, students who need intervention have another level of RTI and I have an authentic way to produce visually appealing content.  ShowMe allows for an educator to use PDFs of notes that match their student's 100%, and take any screen shot and import to annotate.  I have hit around 30,000 views in my three years of using ShowMe as a smartboard and I am very grateful for what I can accomplish with this fiscally cheap, yet luxurious application.",
            profilePictureUrl: "./public/images/testimonials/colin_ohaire.jpg"
        },
        {
            name: "Shauna O'Flynn",
            signature: "Math teacher at Pearl River Middle School",
            testimonial: "I was hesitant at first to use Showme, however now I cannot imagine my classroom without it!  I use it to reteach lessons so students can reinforce lessons at home.  It even helps parents help their children better at home.   I leave the videos embedded on my website for the whole school year so students can refer back to them as needed.  I also use it when I am going to be absent from class so that my students don't miss a day of math class.  At different points in the year I even have the students create accounts and create their own showme videos (with parental permission of course!)  Students become experts on a topic when they have to teach it!  It is a fantastic app!",
            profilePictureUrl: "./public/images/testimonials/shauna_oflynn.jpg"
        },
        {
            name: "Barbara Edwards",
            signature: "",
            testimonial: "My primary use of ShowMe is initially for flipping the classroom.   Students watch a short video prior to coming to class.  The purpose is to move students to creating the flipped videos - making them responsible for their own learning and the ease of the ShowMe app is perfect for this use.  I travel around the county now, serving five different middle schools.   Not only am I able to virtually visit the students everyday, but I can also instruct the teachers!     If I am supplementing or enriching instruction, I can quickly create a ShowMe to share.   There are other apps with more bells and whistles but ShowMe is the one I go to because it's so quick and simple.",
            profilePictureUrl: "./public/images/testimonials/barbara_edwards.jpg"
        },
        {
            name: "Stacey Pearson",
            signature: "6th and 7th grade math, North Carolina",
            testimonial: "I flip my classroom and have found ShowMe to be invaluable. I can make videos at home in my pajamas to be used the next day! The feature I have the most fun with is image search on the web. A nugget of wisdom to share with new members would be to duplicate your slides before recording that way if you need to rerecord the entire video you don't have to create the slides from scratch.",
            profilePictureUrl: "./public/images/testimonials/stacey_pearson.jpg"
        }
    ];
    
    
    $scope.testimonialsActiveSlide = 0;
    
    $scope.testimonialsSlidesContainer = angular.element(document.querySelectorAll('.sm-testimonials-slides-container'));
    $scope.testimonialsSlidesCount = 6;
    
    
    console.log($scope.testimonialsSlidesContainer);
    console.log($scope.testimonialsSlidesCount);
    $scope.nextTestimonial = function () {
        if ($scope.testimonialsActiveSlide < $scope.testimonialsSlidesCount - 1) {
            $scope.testimonialsActiveSlide++;
            $scope.transformTranslateX($scope.testimonialsSlidesContainer, $scope.testimonialsActiveSlide * 400)
        }
        
    };
    
    $scope.switchToSearch = function () {
        $scope.activeSearch = !$scope.activeSearch;
        $scope.searchInputFocus = $scope.activeSearch;
        if(!$scope.activeSearch) {
            $scope.searched = '';
        }
    };
    
    $scope.onKeyDownSearchInput = function (event) {
        if (event.which == 13 || event.keyCode == 13) {
            $scope.searchRedirect();
        }else if(event.which == 27 || event.keyCode == 27) {
            $scope.switchToSearch();
        }
    };
    
    $scope.searchRedirect = function () {
        if($scope.searched != ''){
            $window.location.href = 'http://www.showme.com/search/?q=' + $scope.searched;
        }
    };
    
    $scope.previousTestimonial = function () {
        if ($scope.testimonialsActiveSlide !== 0) {
            $scope.testimonialsActiveSlide--;
            $scope.transformTranslateX($scope.testimonialsSlidesContainer, $scope.testimonialsActiveSlide * 400)
        }
    };
    
    $scope.transformTranslateX = function (element, length) {
        angular.element(element).css('transform', "translateX(-" + length + "px)");
    }
}]);
